-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYezKIfk5Z4I9I6O/
JcVJJF5bwkYMV2yxfNAE+qqAg/ugCgYIKoZIzj0DAQehRANCAASMEuJjVaB5TCIc
MJMSKnC4eHhxvSn1ayR7UB5FS+NOTIFagpD6c5CaWGs3Fo5LebGxSOm4+tQeNPCg
fkyLjcol
-----END PRIVATE KEY-----