name: Android - Production - Build and Deploy

on:
  push:
    branches: ['master']

jobs:
  build-android:
    name: Build Android in Production Environment
    runs-on: react-native
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Inject Keystore
        run: echo "$KEY_STORE" | base64 --decode > "$(pwd)/android/app/wego.keystore"
        shell: bash
        env:
          KEY_STORE: ${{secrets.KEY_STORE}}
      - name: Print Production Env
        run: echo "$ENV_PRODUCTION" > .env.production
        shell: bash
        env:
          ENV_PRODUCTION: ${{secrets.ENV_PRODUCTION}}
      - name: Yarn Install
        run: yarn install
      - name: Bundle Install
        run: bundle install
      - name: Build Android Production
        run: yarn build:android:production:bundle && bundle exec fastlane android distribute_firebase_production